
var friendsArray = [
    {
        "name":"Michael",
        "photo":"https://randomuser.me/api/portraits/men/1.jpg",
        "scores":[
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1
          ]
      },
      {
        "name":"David",
        "photo":"https://randomuser.me/api/portraits/men/2.jpg",
        "scores":[
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2
          ]
      },
      {
        "name":"Randy",
        "photo":"https://randomuser.me/api/portraits/men/3.jpg",
        "scores":[
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3
          ]
      },
      {
        "name":"Robert",
        "photo":"https://randomuser.me/api/portraits/men/4.jpg",
        "scores":[
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4
          ]
      },
      {
        "name":"Mark",
        "photo":"https://randomuser.me/api/portraits/men/5.jpg",
        "scores":[
            5,
            5,
            5,
            5,
            5,
            5,
            5,
            5,
            5,
            5
          ]
      },
    {
        "name":"Anna",
        "photo":"https://randomuser.me/api/portraits/women/1.jpg",
        "scores":[
            3,
            1,
            4,
            4,
            5,
            4,
            3,
            4,
            3,
            1
          ]
      },
      {
        "name":"Isabella",
        "photo":"https://randomuser.me/api/portraits/women/2.jpg",
        "scores":[
            5,
            1,
            4,
            4,
            5,
            1,
            2,
            5,
            4,
            1
          ]
      },
      {
        "name":"Olivia",
        "photo":"https://randomuser.me/api/portraits/women/3.jpg",
        "scores":[
            3,
            4,
            5,
            4,
            2,
            3,
            4,
            1,
            4,
            5
          ]
      },
      {
        "name":"Emma",
        "photo":"https://randomuser.me/api/portraits/women/4.jpg",
        "scores":[
            4,
            5,
            2,
            3,
            1,
            4,
            2,
            4,
            3,
            2
          ]
      },
      {
        "name":"Ashley",
        "photo":"https://randomuser.me/api/portraits/women/5.jpg",
        "scores":[
            2,
            4,
            3,
            4,
            1,
            4,
            3,
            4,
            5,
            1
          ]
      }
]

module.exports = friendsArray;




